### ISSUE TITLE
参数设置完，执行时报错

### ISSUE THREAD

**Issue by eigeen** [Mania-Visualization-Project/Mania-Replay-Master#3]
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.util.MissingResourceException: Can't find bundle for base name res/language, locale zh_CN
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
        at java.util.ResourceBundle.getBundleImpl(Unknown Source)
        at java.util.ResourceBundle.getBundle(Unknown Source)
        at me.replaymaster.Main.<clinit>(Main.kt:14)
```
64位Java

**Comment by Keytoyze** [comment]
你这Java版本看着有点老了，试着更新一下？

**Comment by eigeen** [comment]
```
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```

```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.util.MissingResourceException: Can't find bundle for base name res/language, locale zh_CN
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
        at java.util.ResourceBundle.getBundleImpl(Unknown Source)
        at java.util.ResourceBundle.getBundle(Unknown Source)
        at me.replaymaster.Main.<clinit>(Main.kt:14)
```

更新了版本还是一样

**Comment by eigeen** [comment]
另外，cmd是支持拖拽文件进入窗口释放，自动输入路径的。但是拖拽生成的路径自带双引号，如果按此格式输入会出现问题

**Comment by eigeen** [comment]
已解决，之前将文件放在osu.exe同目录下执行报错，更改位置后运行正常

**Comment by Keytoyze** [comment]
> 另外，cmd是支持拖拽文件进入窗口释放，自动输入路径的。但是拖拽生成的路径自带双引号，如果按此格式输入会出现问题

确实有这个问题，所以用cmd有些麻烦。我搞了个一键渲染器放在同目录里面，你可以参考一下文档试试。
